// 일본 기준: 일요일 시작
export const DAYS = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

export const SOUNDS = [
    { id: "harp01", name: "하프 01", file: "ハープ.mp3" },
    { id: "harp02", name: "하프 02", file: "ハープ02.mp3" },
];

// 언어별 공휴일 키워드
export const HOLIDAY_KEYWORDS = {
    ko: ["신정", "설날", "설", "삼일절", "대통령선거", "국회의원선거", "지방선거", "어린이날", "부처님오신날", "현충일", "광복절", "추석", "개천절", "한글날", "크리스마스", "성탄절", "대체공휴일", "임시공휴일", "공휴일"],
    ja: ["祝日", "元日", "成人の日", "建国記念の日", "天皇誕生日", "春分の日", "昭和の日", "憲法記念日", "みどりの日", "こどもの日", "海の日", "山の日", "敬老の日", "秋分の日", "スポーツの日", "文化の日", "勤労感謝の日", "振替休日", "正月", "ゴールデンウィーク", "お盆"],
    en: ["Holiday", "New Year's Day", "Martin Luther King Jr. Day", "President's Day", "Memorial Day", "Juneteenth", "Independence Day", "Labor Day", "Columbus Day", "Veterans Day", "Thanksgiving", "Christmas", "Bank Holiday", "Public Holiday", "Observed"],
};

export const TRANSLATIONS = {
    ko: {
        settings: "위젯 설정",
        settingsDescription: "원하시는 대로 커스터마이즈해 보세요",
        alwaysOnTop: "항상 위에 표시",
        googleSync: "구글 캘린더 연동",
        autostart: "자동 실행",
        opacity: "배경 투명도",
        alarmSound: "알람 음성",
        language: "언어 설정",
        korean: "한국어",
        japanese: "日本語",
        english: "English",
        save: "저장됐어요",
        delete: "삭제",
        title: "할 일 제목",
        time: "시간 설정",
        repeat: "반복 설정",
        none: "없음",
        weekly: "매주",
        biweekly: "2주마다",
        today: "오늘",
        week: "주차",
        addEvent: "새 할 일 추가",
        editEvent: "할 일 수정",
        free: "일정 없어요",
        holiday: "공휴일",
        lockWidget: "위젯 잠금",
        login: "로그인",
        reset: "연결 해제",
        placeholder: "무엇을 할까요?",
        volume: "볼륨",
        alarmSoon: "10분 후 시작해요",
        apiKeys: "API 키 설정",
        owmApiKey: "OpenWeatherMap API Key",
        openDataFolder: "데이터 폴더 열기",
        clearData: "로컬 데이터 초기화",
        clearDataConfirm: "모든 설정과 일정이 삭제돼요. 계속하시겠어요?",
        checkUpdate: "업데이트 확인",
        updateAvailable: (v: string) => `v${v} 업데이트가 있어요. 설치할까요?`,
        updateNone: "최신 버전이에요.",
        updateInstalling: "설치 중...",
        updateRestartPrompt: "업데이트가 설치됐어요. 지금 재시작할까요?",
        syncSuccess: "캘린더 동기화 완료",
        syncFailed: "캘린더 동기화 실패",
        eventSaved: "일정이 저장됐어요",
        eventUpdated: "일정이 수정됐어요",
        eventDeleted: "일정이 삭제됐어요",
        eventFailed: "일정 저장에 실패했어요",
        owmKeyMissing: "날씨 API 키를 설정해 주세요",
        owmKeyInvalid: "날씨 API 키가 올바르지 않아요",
        sessionExpiredPrompt: "구글 로그인이 만료됐어요. 다시 로그인해 주세요.",
        offline: "네트워크 연결이 끊겼어요",
        online: "네트워크가 복구됐어요",
        confirm: "확인",
        cancel: "취소",
        soundNames: { harp01: "하프 01", harp02: "하프 02" },
    },
    ja: {
        settings: "ウィジェット設定",
        settingsDescription: "経験をカスタマイズしてください",
        alwaysOnTop: "常に最前面に表示",
        googleSync: "Googleカレンダー連携",
        autostart: "自動起動",
        opacity: "背景の透明度",
        alarmSound: "アラーム音",
        language: "言語設定",
        korean: "한국어",
        japanese: "日本語",
        english: "English",
        save: "保存完了",
        delete: "削除",
        title: "予定のタイトル",
        time: "時間設定",
        repeat: "繰り返し設定",
        none: "なし",
        weekly: "毎週",
        biweekly: "2週間ごと",
        today: "今日",
        week: "週目",
        addEvent: "予定を追加",
        editEvent: "予定を編集",
        free: "予定なし",
        holiday: "祝日",
        lockWidget: "ウィジェットロック",
        login: "ログイン",
        reset: "連携解除",
        placeholder: "何をしようか？",
        volume: "音量",
        alarmSoon: "10分後に開始",
        apiKeys: "APIキー設定",
        owmApiKey: "OpenWeatherMap APIキー",
        openDataFolder: "データフォルダを開く",
        clearData: "ローカルデータをリセット",
        clearDataConfirm: "すべての設定と予定が削除されます。続けますか？",
        checkUpdate: "アップデート確認",
        updateAvailable: (v: string) => `v${v} のアップデートがあります。インストールしますか？`,
        updateNone: "最新バージョンです。",
        updateInstalling: "インストール中...",
        updateRestartPrompt: "アップデートが完了しました。今すぐ再起動しますか？",
        syncSuccess: "カレンダーを同期しました",
        syncFailed: "カレンダーの同期に失敗しました",
        eventSaved: "予定を保存しました",
        eventUpdated: "予定を更新しました",
        eventDeleted: "予定を削除しました",
        eventFailed: "予定の保存に失敗しました",
        owmKeyMissing: "天気APIキーを設定してください",
        owmKeyInvalid: "天気APIキーが正しくありません",
        sessionExpiredPrompt: "Googleログインの有効期限が切れました。再ログインしてください。",
        offline: "ネットワーク接続が切断されました",
        online: "ネットワークが回復しました",
        confirm: "確認",
        cancel: "キャンセル",
        soundNames: { harp01: "ハープ 01", harp02: "ハープ 02" },
    },
    en: {
        settings: "Settings",
        settingsDescription: "Customize your experience",
        alwaysOnTop: "Always on Top",
        googleSync: "Google Calendar Sync",
        autostart: "Auto Start",
        opacity: "Background Transparency",
        alarmSound: "Notification Sound",
        language: "Language",
        korean: "한국어",
        japanese: "日本語",
        english: "English",
        save: "Saved",
        delete: "Delete",
        title: "Task Title",
        time: "Set Time",
        repeat: "Repeat",
        none: "None",
        weekly: "Weekly",
        biweekly: "Bi-weekly",
        today: "Today",
        week: "Week",
        addEvent: "Add Task",
        editEvent: "Edit Task",
        free: "No Tasks",
        holiday: "Holiday",
        lockWidget: "Lock Widget",
        login: "Login",
        reset: "Disconnect",
        placeholder: "What to do?",
        volume: "Volume",
        alarmSoon: "Starting in 10 min",
        apiKeys: "API Keys",
        owmApiKey: "OpenWeatherMap API Key",
        openDataFolder: "Open Data Folder",
        clearData: "Clear Local Data",
        clearDataConfirm: "All settings and tasks will be deleted. Continue?",
        checkUpdate: "Check for Updates",
        updateAvailable: (v: string) => `v${v} is available. Install now?`,
        updateNone: "You're on the latest version.",
        updateInstalling: "Installing...",
        updateRestartPrompt: "Update installed. Restart now?",
        syncSuccess: "Calendar synced",
        syncFailed: "Calendar sync failed",
        eventSaved: "Event saved",
        eventUpdated: "Event updated",
        eventDeleted: "Event deleted",
        eventFailed: "Failed to save event",
        owmKeyMissing: "Please set your weather API key",
        owmKeyInvalid: "Invalid weather API key",
        sessionExpiredPrompt: "Google login expired. Please log in again.",
        offline: "Network connection lost",
        online: "Network restored",
        confirm: "Confirm",
        cancel: "Cancel",
        soundNames: { harp01: "Harp 01", harp02: "Harp 02" },
    },
};
