// 일본 기준: 일요일 시작
export const DAYS = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

export const SOUNDS = [
    { id: "harp01", name: "하프 01", file: "ハープ.mp3" },
    { id: "harp02", name: "하프 02", file: "ハープ02.mp3" },
];

// 언어별 공휴일 키워드
export const HOLIDAY_KEYWORDS = {
    ko: ["신정", "설날", "설", "삼일절", "대통령선거", "국회의원선거", "지방선거", "어린이날", "부처님오신날", "현충일", "광복절", "추석", "개천절", "한글날", "크리스마스", "성탄절", "대체공휴일", "임시공휴일", "공휴일"],
    ja: ["祝日", "元日", "成人の日", "建国記念の日", "天皇誕生日", "春分の日", "昭和の日", "憲法記念日", "みどりの日", "こどもの日", "海の日", "山の日", "敬老の日", "秋分の日", "スポーツの日", "文化の日", "勤労感謝の日", "振替休日", "正月", "ゴールデンウィーク", "お盆"],
    en: ["Holiday", "New Year's Day", "Martin Luther King Jr. Day", "President's Day", "Memorial Day", "Juneteenth", "Independence Day", "Labor Day", "Columbus Day", "Veterans Day", "Thanksgiving", "Christmas", "Bank Holiday", "Public Holiday", "Observed"],
};

export const TRANSLATIONS = {
    ko: {
        settings: "위젯 설정",
        settingsDescription: "원하시는 대로 커스터마이즈해 보세요",
        alwaysOnTop: "항상 위에 표시",
        googleSync: "구글 캘린더 연동",
        autostart: "자동 실행",
        opacity: "배경 투명도",
        alarmSound: "알람 음성",
        language: "언어 설정",
        korean: "한국어",
        japanese: "日本語",
        english: "English",
        save: "저장됐어요",
        delete: "삭제",
        title: "할 일 제목",
        time: "시간 설정",
        repeat: "반복 설정",
        none: "없음",
        weekly: "매주",
        biweekly: "2주마다",
        today: "오늘",
        week: "주차",
        addEvent: "새 할 일 추가",
        editEvent: "할 일 수정",
        free: "일정 없어요",
        holiday: "공휴일",
        lockWidget: "위젯 잠금",
        login: "로그인",
        reset: "연결 해제",
        placeholder: "무엇을 할까요?",
        soundTip: "* 클릭하면 미리 들을 수 있어요",
        alarmSoon: "10분 후 시작해요",
        googleLoginPrompt: "구글 로그인 후 주소창의 code= 이후 부분을 복사해서 붙여넣어 주세요:",
        sessionExpired: "구글 로그인 세션이 만료됐어요. 다시 로그인해 주세요.",
        apiKeys: "API 키 설정",
        googleClientId: "Google Client ID",
        googleClientSecret: "Google Client Secret",
        owmApiKey: "OpenWeatherMap API Key",
        openDataFolder: "데이터 폴더 열기",
        clearData: "로컬 데이터 초기화",
        clearDataConfirm: "모든 설정과 일정이 삭제돼요. 계속하시겠어요?",
        soundNames: { harp01: "하프 01", harp02: "하프 02" },
    },
    ja: {
        settings: "ウィジェット設定",
        settingsDescription: "経験をカスタマイズしてください",
        alwaysOnTop: "常に最前面に表示",
        googleSync: "Googleカレンダー連携",
        autostart: "自動起動",
        opacity: "背景の透明度",
        alarmSound: "アラーム音",
        language: "言語設定",
        korean: "한국어",
        japanese: "日本語",
        english: "English",
        save: "保存完了",
        delete: "削除",
        title: "予定のタイトル",
        time: "時間設定",
        repeat: "繰り返し設定",
        none: "なし",
        weekly: "毎週",
        biweekly: "2週間ごと",
        today: "今日",
        week: "週目",
        addEvent: "予定を追加",
        editEvent: "予定を編集",
        free: "予定なし",
        holiday: "祝日",
        lockWidget: "ウィジェットロック",
        login: "ログイン",
        reset: "連携解除",
        placeholder: "何をしようか？",
        soundTip: "* クリックでプレビュー再生",
        alarmSoon: "10分後に開始",
        googleLoginPrompt: "Googleログイン後、アドレスバーの code= 以降をコピーして入力してください:",
        sessionExpired: "セッションが期限切れです。もう一度ログインしてください。",
        apiKeys: "APIキー設定",
        googleClientId: "Google Client ID",
        googleClientSecret: "Google Client Secret",
        owmApiKey: "OpenWeatherMap APIキー",
        openDataFolder: "データフォルダを開く",
        clearData: "ローカルデータをリセット",
        clearDataConfirm: "すべての設定と予定が削除されます。続けますか？",
        soundNames: { harp01: "ハープ 01", harp02: "ハープ 02" },
    },
    en: {
        settings: "Settings",
        settingsDescription: "Customize your experience",
        alwaysOnTop: "Always on Top",
        googleSync: "Google Calendar Sync",
        autostart: "Auto Start",
        opacity: "Background Transparency",
        alarmSound: "Notification Sound",
        language: "Language",
        korean: "한국어",
        japanese: "日本語",
        english: "English",
        save: "Saved",
        delete: "Delete",
        title: "Task Title",
        time: "Set Time",
        repeat: "Repeat",
        none: "None",
        weekly: "Weekly",
        biweekly: "Bi-weekly",
        today: "Today",
        week: "Week",
        addEvent: "Add Task",
        editEvent: "Edit Task",
        free: "No Tasks",
        holiday: "Holiday",
        lockWidget: "Lock Widget",
        login: "Login",
        reset: "Disconnect",
        placeholder: "What to do?",
        soundTip: "* Click to preview",
        alarmSoon: "Starting in 10 min",
        googleLoginPrompt: "After logging in to Google, copy the code from the URL and paste it:",
        sessionExpired: "Session expired. Please log in again.",
        apiKeys: "API Keys",
        googleClientId: "Google Client ID",
        googleClientSecret: "Google Client Secret",
        owmApiKey: "OpenWeatherMap API Key",
        openDataFolder: "Open Data Folder",
        clearData: "Clear Local Data",
        clearDataConfirm: "All settings and tasks will be deleted. Continue?",
        soundNames: { harp01: "Harp 01", harp02: "Harp 02" },
    },
};
